baseURL = '/'
languageCode = 'en-us'
title = 'TimDbg'
theme = "m10c"
googleAnalytics = "G-ZF3NN3CLRX"

[params]
  author = "Tim Misiak"
  description = "The art and science of debugging. Windows debugging tips from a WinDbg dev"
  favicon = "WinDbg.ico"
  avatar = "avatar.jpg"

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"

[[params.social]]
  icon = "github"
  name = "Github"
  url = "https://github.com/timmisiak"

[[params.social]]
  icon = "twitter"
  name = "Twitter"
  url = "https://twitter.com/timmisiak"
