baseURL = '/'
languageCode = 'en-us'
title = 'TimDbg'
theme = "m10c"
googleAnalytics = "G-ZF3NN3CLRX"

rssLimit = 20
copyright = "2022 Tim Misiak"

[author]
  name = "Tim Misiak"

[params]
  author = "Tim Misiak"
  description = "The art and science of debugging. And other stuff like that. From a former developer on WinDbg and the VMware hypervisor."
  favicon = "WinDbg.ico"
  avatar = "avatar.jpg"

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"

[[params.social]]
  icon = "github"
  name = "Github"
  url = "https://github.com/timmisiak"

[[params.social]]
  icon = "twitter"
  name = "Twitter"
  url = "https://twitter.com/timmisiak"

[[params.social]]
  icon = "youtube"
  name = "YouTube"
  url = "https://www.youtube.com/channel/UCyQ7p63-9V9PZJvgHLKgsaw"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
